version: '3.8'

services:
  php-app:
    build: .
    container_name: otbchessresults
    ports:
      - "8085:80"
    volumes:
      - ./public:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./vendor:/var/www/html/vendor
      - php_composer_cache:/root/.composer/cache
    networks:
      - matrix
    restart: unless-stopped
    command: >
      sh -c "if [ ! -d /var/www/html/vendor ] || [ -z \"$$\(ls -A /var/www/html/vendor\)\" ]; then
        composer install --optimize-autoloader --no-interaction;
      fi && chown -R www-data:www-data /var/www/html/vendor && exec docker-php-entrypoint apache2-foreground"

volumes:
  php_composer_cache:


networks:
  matrix:
    external: true
